version: '3.8'
services:
  database:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todo
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
